### ISSUE TITLE
Future functionality of the package

### ISSUE THREAD

**Issue by walkerke** [walkerke/bsselectR#2]
I've got the package operational enough for what I need it to do; at this point I'll probably hack on it from time to time and eventually submit to CRAN.  I'd like to add the following: 

- [ ] Support for custom styling of dropdown elements; 
- [ ] Support for icons next to element names; 
- [ ] Multiple selections and multiple displays; 
- [ ] Subtext next to menu options
- [ ] Groups within dropdown menus

**Comment by jtpoirier** [comment]
This is a great package. It would be amazing if 1 dropdown menu could change multiple graphs. Is this a possibility?

**Comment by walkerke** [comment]
@jtpoirier I'm not really working on this package at the moment as I have other higher-priority projects.  If anyone out there comes across this issue and wants to take over this package, they are welcome to do so.
