### ISSUE TITLE
Plots not updating

### ISSUE THREAD

**Issue by scriscio** [walkerke/bsselectR#3]
Hi,  I was trying to use this example in an HTML R markdown.  I have the dropdown menu working, but the plots I created do not seem to be updating from the pre-selected plot.  Let me know if you have any ideas.

**Comment by walkerke** [comment]
Could you provide a reproducible example?  It's tough to debug this without seeing your code.

**Comment by scriscio** [comment]
Unfortunately, I cannot share.  I think you can close this as an issue.
