### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by riccardopinosio** [walkerke/bsselectR#5]
Hello,

This is a very interesting project, I was wondering what its status is. 
I am thinking about writing an htmlwidget package with bindings to the select2 javascript library https://select2.org/ and bootstrap select library, with the idea of providing a superset of the functionalities that your bsselectR package offers and the possibility of using this as input in shiny.
Would it make sense to merge the two projects? I have just begun working here:

https://github.com/riccardopinosio/selectR 

But it would be awesome to reuse you code as a basis.

R.

**Comment by walkerke** [comment]
I don't have any plans to re-start work on this project anytime soon.  You are welcome to use any of the code I've written in your project!

**Comment by riccardopinosio** [comment]
Awesome, then I'll do that (obviously referencing your work in any way required)
R.
