### ISSUE TITLE
issue displaying type="img"

### ISSUE THREAD

**Issue by istallworthy** [walkerke/bsselectR#7]
Hi there, 

I have been attempting to create an interactive figure using these guidelines (https://walkerke.github.io/2016/12/rmd-dropdowns/) and for some reason I am only ever getting a picture of an image icon (attached) for each of my drop-down figures instead of the actual figure. My figures are saving to my subdirectory successfully and I have no idea why this occurs (I have also tried several image types). Would love some help!

Thanks,
Isa

![Screen Shot 2020-04-23 at 9 21 56 AM](https://user-images.githubusercontent.com/31548151/80110106-f05ab180-8543-11ea-8646-1b8aae980466.png)

**Comment by walkerke** [comment]
Hi @istallworthy - it's tough to debug this without your code & a reproducible example.  Can you share more?  I'd also recommend right-clicking the broken image in your browser and choosing "open image in new tab" and seeing where the browser is looking for the image.

**Comment by istallworthy** [comment]
Thank you for your help! I have attached code below: 

````{r, echo=FALSE}
library(purrr)
# treat=c(treatments)
# devtools::install_github("walkerke/bsselectR")

#makes histogram plots of all tx final weights
plots=lapply(treatments, function(x) {

  treat=get(paste(x, "_mean_weight_all_imp", sep=""))

#Writes image of histogram
p=ggplot(data=as.data.frame(treat_mean), aes(x = as.numeric(treat))) +
  geom_histogram(color = 'black')

p

})

paths=paste0(treatments, ".png")
setwd("/Users/isabella/Desktop/BSL Lab/FLP/Scarcity and dev/")
dir.create("plots")
pwalk(list(paths, plots), ggsave, path = "plots", dpi = 300) #these are successfully saved

library(stringr)
library(htmlwidgets)
library(bsselectR)
state_plots <- paste0(list.files("plots", full.names = TRUE))
names(state_plots) <- str_replace_all(state_plots,
                                      c("\\.png" = "",
                                        "plots/" = ""))


bsselect(state_plots, type = "img", selected="INR",
          live_search = TRUE, show_tick = TRUE)

````
Output:

![Screen Shot 2020-04-23 at 9 48 58 AM](https://user-images.githubusercontent.com/31548151/80113406-e3d85800-8547-11ea-938b-9343911803a0.png)

I am just attempting to pull in 3 standard .png images from a local folder (can attach these too if that would be helpful). 

Thanks again!

**Comment by istallworthy** [comment]
Update on this: the error only shows when running the code chunk individually but it actually works just fine when knitting the whole thing --not sure why!

**Comment by walkerke** [comment]
glad to hear it is working!  with regards to running the code chunk individually - I wonder if it has something to do with how R Markdown is handling paths.  I'm not actively developing this package at the moment, so hopefully it does what you need for now.
